stages:
  - build
  - test
  - deploy

job 1:
  stage: build
  script: sleep 1

job 2:
  stage: build
  script: sleep 2

job 3:
  stage: test
  script: sleep 1

job 4:
  stage: deploy
  script: sleep 1
